from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. Alembic needs it to run migrations -- "
            "export your Neon connection string before running `alembic upgrade head`."
        )
    # A plain "postgresql://" scheme makes SQLAlchemy default to psycopg2,
    # which this project does not depend on -- psycopg[binary] in
    # pyproject.toml is psycopg3. Force the psycopg3 dialect explicitly.
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    elif url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql+psycopg://", 1)
    return url


# This module is only ever imported by the `alembic` CLI, never by the API
# app or the test suite, so requiring DATABASE_URL here does not violate the
# "no test needs real credentials" rule the rest of the codebase follows.
config.set_main_option("sqlalchemy.url", _database_url())

# Migrations are hand-written (op.create_table) rather than autogenerated
# from ORM models -- the app layer uses raw psycopg, not an ORM -- so there
# is no metadata object to diff against.
target_metadata = None


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection (`alembic upgrade head --sql`)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
